@startuml

class Usuario {
    -email: String
    -login: String
    -senha: string
}

class Cartao{
    -numero: String
    -dataValidade: String
}

enum BandeiraCartao{
    -VISA: int
    -MASTERCARD: int
    -ELO: int
    -AMERICAN_EXPRESS: int

}

class Endereco{
    -descricao: String
    -numero: String
    -rua: String
    -cep: String
}

class Cidade{

}

class Estado{

}

class PessoaFisica {
    -cpf: String
    -dataNascimento: Date
}

class PessoaJuridica {
    -cnpj: String

}

class Telefone{

}

class Produto {
    -preco: Double

}

class Bike {
    -tamanho: int
    -marcha: int
    -freio: String
    -cambio: String
    -aro: int
    -observacao: String
}

class Marca{

}

class TipoBike{

}

class Carrinho{
    -precoFinal: Double

}

class Compra{
    -valorTotal: Double
    
}

class Pagamento{
    -token: String
    -pago: Boolean
    -codigo: String
}

enum FormaPagamento{
    -PIX: int
    -CARTAO_DEBITO: int
    -CARTAO_CREDITO: int
    -BOLETO: int
}

class Pedido{
    -dataPrevista: String
    -dataEntrega: String
}

enum statusPedido{
    -PREPARANDO: int 
    -EM_ROTA: int 
    -ENTREGUE: int 
    -FINALIZADO: int 
    -CANCELADO: int 
}

class Avaliacao{
    -estrela: int
    -comentario: String
}


class Cupom{
    -desconto: Double
    -valorMinimo: Double
}

class Cor{

}

class Tamanho{

}

class Estoque {
    -quantidade: int

}

class ListaProduto{
    -quantidade: int

}


Cidade "*" o--> "1" Estado
Endereco "*" o--> "1" Cidade

Carrinho "*" o--> "1" Cupom
Carrinho "1" *--> "*" ListaProduto
Carrinho "*" *--> "1" Usuario

Cupom "*" --> "*" Produto: listaProdutosCupom

Compra "*" o--> "1" Endereco
Compra --|> Carrinho
Pagamento --|> Compra

Pedido "*" o--> "1" statusPedido
Pedido --|> Pagamento
Pedido "1" *--> "*" Avaliacao

Avaliacao "*" o--> "1" Produto

Pagamento "*" --> "1" FormaPagamento
Pagamento "*" o--> "1" Cartao

Cartao "*" --> "1" BandeiraCartao
Usuario "1" *--> "*" Cartao 
Usuario "1" *--> "*" Endereco
Usuario "1" *--> "*" Telefone

ListaProduto "*" o--> "1" Produto

Produto "*" o--> "1" Cor
Produto "*" o--> "1" Tamanho

Bike --|> Produto
Bike "*" o--> "1" Marca
Bike "*" o--> "1" TipoBike

Usuario "*" --> "*" Produto: listaDesejos
PessoaFisica --|> Usuario
PessoaJuridica --|> Usuario
PessoaJuridica "1" o--> "*" PessoaFisica
Produto "1" *--> "1" Estoque


@enduml