@startuml

class Usuario {
    -nome: String
    -email: String
    -login: String
    -senha: string
}

class Cartao{
    -nome: String
    -numero: String
    -dataValidade: String
}

enum BandeiraCartao{
    -VISA: int
    -MASTERCARD: int
    -ELO: int
    -AMERICAN_EXPRESS: int

}

class Endereco{
    -nome: String
    -descricao: String
    -numero: String
    -rua: String
    -cep: String
}

class Cidade{
    -nome: String

}

class Estado{
    -nome: String
    -sigla: String
}

class PessoaFisica {
    -cpf: String
    -dataNascimento: Date
}

class Telefone{
    -codigoArea: Integer
    -numero: Long
}

class Produto {
    -nome: String
    -preco: Double
    -estoque: Integer

}

class Bike {
    -marcha: int
    -freio: String
    -cambio: String
    -observacao: String
}

class Marca {
    -nome: String
    -urlSite: String
    -urlLogo: String
}

class Fornecedor {
    -nome: String
    -cnpj: String
}

class Freio {
    -nome: String
}

class Pneu {

}

class Aro {
    -nome: String
}

enum TipoBike{
    - ROAD_BIKE: int
    - MOUNTAIN_BIKE: int
    - HYBRID_BIKE: int
    - ELECTRIC_BIKE: int
    - FOLDING_BIKE: int
    - CITY_OR_CRUISER_BIKE: int
    - TRIATHLON_BIKE: int
    - BMX_BIKE: int
    - CYCLOCROSS_BIKE: int
    - TOURING_BIKE: int
}

enum Tamanho{
    -A4: int
    -A5: int
    -A8: int
    -A12: int
    -A16: int
    -A18: int
    -A20: int
    -A22: int
    -A24: int
    -A26: int
    -A27: int
    -A27_5: int
    -A28: int
    -A29: int
    -A650B: int
    -A700C: int
    -A_OUTRO: int

}

class Compra{
    -valorTotal: Double
    -token: String
    -pago: Boolean
    -codigoRastreio: String
    -dataPrevista: String
    -dataEntrega: String
}


enum FormaPagamento{
    -PIX: int
    -CARTAO_DEBITO: int
    -CARTAO_CREDITO: int
    -BOLETO: int
}

enum StatusPedido{
    -PREPARANDO: int
    -EM_ROTA: int
    -ENTREGUE: int
    -FINALIZADO: int
    -CANCELADO: int
}

class Avaliacao{
    -estrela: int
    -comentario: String
}


class Cupom{
    -nome: String
    -codigo: String
    -desconto: Double
    -valorMinimo: Double
}

enum Cor{
    -Vermelho: int
    -Laranja: int
    -Amarelo: int
    -Verde: int
    -Azul: int
    -Roxo: int
    -Rosa: int
    -Preto: int
    -Branco: int
    -Cinza: int
}

class Categoria{
    -nome: String
}

class ItemCompra{
    -quantidade: Integer
    -preco: Double

}

class Ferramenta{

}


Cidade "*" *--> "1" Estado
Endereco "*" o--> "1" Cidade

Compra "*" o--> "1" Cupom
Compra "1" *--> "*" ItemCompra
Compra "*" *--> "1" Usuario

Cupom "*" o--> "*" Produto: ItemComprasCupom

Compra "*" o--> "1" Endereco

Compra "*" o--> "1" StatusPedido

Produto "1" o--> "*" Avaliacao

Avaliacao "*" o--> "1" Usuario

Compra "*" o--> "1" FormaPagamento
Compra "*" o--> "1" Cartao

Cartao "*" o--> "1" BandeiraCartao
Cartao "*" *--> "1" Usuario
Endereco "*" *--> "1" Usuario
Telefone "*" *--> "1" Usuario

ItemCompra "*" *--> "1" Produto

Produto "*" o--> "1" Cor

Ferramenta --|> Produto

Bike --|> Produto
Bike "*" o--> "1" Tamanho
Bike "*" o--> "1" TipoBike
Bike "*" --> "1" Freio

Produto "*" o--> "1" Marca
Marca "*" --> "1" Fornecedor

Pneu --|> Produto

Pneu "*" o--> "1" Aro

Usuario "*" --> "*" Produto: listaDesejos
PessoaFisica --|> Usuario

Produto "*" o--> "*" Categoria


@enduml